### PR TITLE
Replace depreciated .show()

### LINKED ISSUE #14: Convert .show() to .root_group = for CircuitPython 9

### PR DESCRIPTION
**Pull request by RetiredWizard**
fixes #14

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
The examples set the .root_group to None and them figure out the root_group and set the root_group to that thing. I'm thinking the None assignment is unnecessary?

**Comment by RetiredWizard** [comment]
Since I'm not actually testing the code, I'm a little concerned about making logic changes. One of the root_group=None lines has a sleep following it. Do you think it's possible removing the screen blanks may change the way the display behaves, especially on slower microcontrollers/displays (maybe e-ink)?

When I went back and looked through the example code this time, I did notice that at least one of the examples is using a secrets file rather than settings.toml. I think I should go ahead and add logic to check if the settings.toml is there and if it is, use that instead. The secrets.py should probably stay in as a fall back since the examples may be referenced by learn guides that haven't been updated for settings.toml?

**Comment by dhalbert** [comment]
Yes, that's the problem with looking at old code :smile:

**Review by dhalbert — APPROVED** [review]
We decided to leave the `None`s in for now, since the code will still work.

**Comment by RetiredWizard** [comment]
I'll submit a second PR to this library for the secrets.py fix. I think this one can be merged.

**Pull request merged**
